#!/usr/bin/env python
"""Per-class LaTeX tables for the final fusion on test.

Two tabulars are emitted (printed to stdout and written to
figures/per_class_table.tex):
  1. Rare classes (78, 34, 80): support, precision, recall, macro-F1.
  2. Major confusion pairs:
       14 <-> 86   (bidirectional)
       61 <-> 90   (bidirectional)
       34  -> 56   (one-directional, true=34 pred=56)
     For each (true, pred) we report the number of test samples.

Reads:
  - expected_outputs/test_full_fusion.csv  (anonymised_protein_id, predicted_label)
  - 00_data/splits/test_set_ground_truth.csv (anonymised_protein_id, class_id)
"""
import argparse
from pathlib import Path

import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402
from sklearn.metrics import (  # noqa: E402
    confusion_matrix, precision_recall_fscore_support)

PROJ = Path(__file__).resolve().parent.parent
DEFAULT_PRED = PROJ / "expected_outputs" / "test_full_fusion.csv"
DEFAULT_GT = PROJ / "00_data" / "splits" / "test_set_ground_truth.csv"
OUT = PROJ / "figures" / "per_class_table.tex"
N_CLASS = 97

RARE_CLASSES = (78, 34, 80)
# (true, pred, label) -- bidirectional pairs are listed both ways.
CONFUSION_PAIRS = [
    (14, 86, "14 \\rightarrow 86"),
    (86, 14, "86 \\rightarrow 14"),
    (61, 90, "61 \\rightarrow 90"),
    (90, 61, "90 \\rightarrow 61"),
    (34, 56, "34 \\rightarrow 56"),
]


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--pred", default=str(DEFAULT_PRED))
    ap.add_argument("--gt", default=str(DEFAULT_GT))
    ap.add_argument("--out", default=str(OUT))
    args = ap.parse_args()

    pred_df = pd.read_csv(args.pred)
    gt_df = pd.read_csv(args.gt)
    merged = gt_df.merge(pred_df, on="anonymised_protein_id", how="inner")
    if len(merged) != len(gt_df):
        raise SystemExit("row mismatch after merge: gt=%d pred=%d merged=%d"
                         % (len(gt_df), len(pred_df), len(merged)))

    y_true = merged["class_id"].values
    y_pred = merged["predicted_label"].values
    labels = list(range(N_CLASS))
    P, R, F1, S = precision_recall_fscore_support(
        y_true, y_pred, labels=labels, zero_division=0)
    cm = confusion_matrix(y_true, y_pred, labels=labels)

    lines = []
    lines.append("% Auto-generated by 04_analysis/make_per_class_table.py")
    lines.append(r"\begin{table}[h]")
    lines.append(r"\centering")
    lines.append(r"\caption{Rare classes on the test set (final fusion).}")
    lines.append(r"\label{tab:rare-classes}")
    lines.append(r"\begin{tabular}{rrrrr}")
    lines.append(r"\toprule")
    lines.append(r"class & support & precision & recall & F1 \\")
    lines.append(r"\midrule")
    for c in RARE_CLASSES:
        lines.append("%d & %d & %.4f & %.4f & %.4f \\\\"
                     % (c, S[c], P[c], R[c], F1[c]))
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")
    lines.append("")

    lines.append(r"\begin{table}[h]")
    lines.append(r"\centering")
    lines.append(r"\caption{Major confusion pairs on the test set (final fusion).}")
    lines.append(r"\label{tab:confusion-pairs}")
    lines.append(r"\begin{tabular}{lr}")
    lines.append(r"\toprule")
    lines.append(r"direction & \# samples \\")
    lines.append(r"\midrule")
    for t, p, lbl in CONFUSION_PAIRS:
        lines.append("%s & %d \\\\" % (lbl, cm[t, p]))
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")

    tex = "\n".join(lines) + "\n"
    print(tex)
    OUT_P = Path(args.out)
    OUT_P.parent.mkdir(parents=True, exist_ok=True)
    OUT_P.write_text(tex)
    print("saved %s" % OUT_P)


if __name__ == "__main__":
    main()
